# Generated by Django 6.0 on 2026-01-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_safaripackage_price_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.safaripackage')),
            ],
        ),
    ]
