# Generated by Django 6.0 on 2026-01-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_text', models.CharField(help_text='e.g. 3 Days / 2 Nights', max_length=50)),
                ('location', models.CharField(help_text='e.g. Masai Mara', max_length=100)),
                ('image_url', models.URLField(help_text='Paste the Unsplash image link here', max_length=500)),
                ('description', models.TextField()),
                ('price_guideline', models.CharField(blank=True, help_text='e.g. From $400 pp', max_length=100)),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mark as Most Popular')),
                ('is_luxury', models.BooleanField(default=False, verbose_name='Mark as Luxury')),
            ],
        ),
    ]
