# Generated by Django 6.0 on 2026-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL text (e.g., 'masai-mara'). Must be unique.", unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('best_time', models.CharField(help_text='e.g. July to October', max_length=100)),
                ('ideal_stay', models.CharField(help_text='e.g. 3-4 Days', max_length=100)),
                ('wildlife', models.CharField(help_text='e.g. Big 5, Cheetah, Hippo', max_length=200)),
                ('highlights', models.TextField(help_text="Enter highlights separated by commas (e.g., 'Big 5, Hot Air Balloon, Cultural Visits')")),
            ],
        ),
    ]
