# Generated by Django 6.0 on 2026-01-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(default='Safari Traveler', help_text="e.g. 'Family from Texas' or 'Solo Traveler'", max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Optional: Link to client photo')),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='1 to 5 stars')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
