# Generated by Django 6.0 on 2026-01-20 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='e.g. 1, 2, 3')),
                ('title', models.CharField(help_text='e.g. Arrival in Nairobi', max_length=200)),
                ('description', models.TextField()),
                ('accommodation', models.CharField(blank=True, help_text='e.g. Sarova Stanley Hotel', max_length=200, null=True)),
                ('meals', models.CharField(blank=True, help_text='e.g. Breakfast, Lunch, Dinner', max_length=100, null=True)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='core.safaripackage')),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Days',
                'ordering': ['day_number'],
            },
        ),
    ]
