# Generated by Django 6.0 on 2026-01-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_destination_id_alter_inquiry_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='subject',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of Adults'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Number of Children'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Handled?'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='core.safaripackage'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='travel_date',
            field=models.DateField(blank=True, help_text='Approximate travel date', null=True),
        ),
    ]
