# Generated by Django 6.0.1 on 2026-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_inquiry_subject_inquiry_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per person in USD', max_digits=10),
        ),
    ]
